 SET IDENTITY_INSERT Exercises ON;

 INSERT INTO Exercises (Id, Name, MuscleGroup, Description, VideoUrl) VALUES
(1, 'Push-up', 'Chest', 'A basic push-up exercise.', 'https://example.com/push-up'),
(2, 'Squat', 'Legs', 'A basic squat exercise.', 'https://example.com/squat'),
(3, 'Pull-up', 'Back', 'A basic pull-up exercise.', 'https://example.com/pull-up'),
(4, 'Bicep Curl', 'Arms', 'A basic bicep curl exercise.', 'https://example.com/bicep-curl'),
(5, 'Plank', 'Core', 'A basic plank exercise.', 'https://example.com/plank'),
(6, 'Lunge', 'Legs', 'A basic lunge exercise.', 'https://example.com/lunge'),
(7, 'Deadlift', 'Back', 'A basic deadlift exercise.', 'https://example.com/deadlift'),
(8, 'Bench Press', 'Chest', 'A basic bench press exercise.', 'https://example.com/bench-press'),
(9, 'Shoulder Press', 'Shoulders', 'A basic shoulder press exercise.', 'https://example.com/shoulder-press'),
(10, 'Tricep Dip', 'Arms', 'A basic tricep dip exercise.', 'https://example.com/tricep-dip'),
(11, 'Leg Press', 'Legs', 'A basic leg press exercise.', 'https://example.com/leg-press'),
(12, 'Lat Pulldown', 'Back', 'A basic lat pulldown exercise.', 'https://example.com/lat-pulldown'),
(13, 'Crunch', 'Core', 'A basic crunch exercise.', 'https://example.com/crunch'),
(14, 'Russian Twist', 'Core', 'A basic Russian twist exercise.', 'https://example.com/russian-twist'),
(15, 'Calf Raise', 'Legs', 'A basic calf raise exercise.', 'https://example.com/calf-raise'),
(16, 'Leg Curl', 'Legs', 'A basic leg curl exercise.', 'https://example.com/leg-curl'),
(17, 'Leg Extension', 'Legs', 'A basic leg extension exercise.', 'https://example.com/leg-extension'),
(18, 'Chest Fly', 'Chest', 'A basic chest fly exercise.', 'https://example.com/chest-fly'),
(19, 'Hammer Curl', 'Arms', 'A basic hammer curl exercise.', 'https://example.com/hammer-curl'),
(20, 'Side Plank', 'Core', 'A basic side plank exercise.', 'https://example.com/side-plank'),
(21, 'Mountain Climber', 'Core', 'A basic mountain climber exercise.', 'https://example.com/mountain-climber'),
(22, 'Burpee', 'Full Body', 'A basic burpee exercise.', 'https://example.com/burpee'),
(23, 'Dumbbell Row', 'Back', 'A basic dumbbell row exercise.', 'https://example.com/dumbbell-row'),
(24, 'Leg Raise', 'Core', 'A basic leg raise exercise.', 'https://example.com/leg-raise'),
(25, 'Seated Row', 'Back', 'A basic seated row exercise.', 'https://example.com/seated-row'),
(26, 'Chest Press', 'Chest', 'A basic chest press exercise.', 'https://example.com/chest-press'),
(27, 'Overhead Tricep Extension', 'Arms', 'A basic overhead tricep extension exercise.', 'https://example.com/overhead-tricep-extension'),
(28, 'Front Raise', 'Shoulders', 'A basic front raise exercise.', 'https://example.com/front-raise'),
(29, 'Side Lateral Raise', 'Shoulders', 'A basic side lateral raise exercise.', 'https://example.com/side-lateral-raise'),
(30, 'Reverse Fly', 'Back', 'A basic reverse fly exercise.', 'https://example.com/reverse-fly'),
(31, 'Cable Crossover', 'Chest', 'A basic cable crossover exercise.', 'https://example.com/cable-crossover'),
(32, 'Face Pull', 'Shoulders', 'A basic face pull exercise.', 'https://example.com/face-pull'),
(33, 'Incline Bench Press', 'Chest', 'A basic incline bench press exercise.', 'https://example.com/incline-bench-press'),
(34, 'Decline Bench Press', 'Chest', 'A basic decline bench press exercise.', 'https://example.com/decline-bench-press'),
(35, 'Dumbbell Fly', 'Chest', 'A basic dumbbell fly exercise.', 'https://example.com/dumbbell-fly'),
(36, 'Arnold Press', 'Shoulders', 'A basic Arnold press exercise.', 'https://example.com/arnold-press'),
(37, 'Bent Over Row', 'Back', 'A basic bent over row exercise.', 'https://example.com/bent-over-row'),
(38, 'T-Bar Row', 'Back', 'A basic T-bar row exercise.', 'https://example.com/t-bar-row'),
(39, 'Good Morning', 'Back', 'A basic good morning exercise.', 'https://example.com/good-morning'),
(40, 'Hip Thrust', 'Glutes', 'A basic hip thrust exercise.', 'https://example.com/hip-thrust'),
(41, 'Glute Bridge', 'Glutes', 'A basic glute bridge exercise.', 'https://example.com/glute-bridge'),
(42, 'Donkey Kick', 'Glutes', 'A basic donkey kick exercise.', 'https://example.com/donkey-kick'),
(43, 'Fire Hydrant', 'Glutes', 'A basic fire hydrant exercise.', 'https://example.com/fire-hydrant'),
(44, 'Step-Up', 'Legs', 'A basic step-up exercise.', 'https://example.com/step-up'),
(45, 'Box Jump', 'Legs', 'A basic box jump exercise.', 'https://example.com/box-jump'),
(46, 'Pistol Squat', 'Legs', 'A basic pistol squat exercise.', 'https://example.com/pistol-squat'),
(47, 'Bulgarian Split Squat', 'Legs', 'A basic Bulgarian split squat exercise.', 'https://example.com/bulgarian-split-squat'),
(48, 'Goblet Squat', 'Legs', 'A basic goblet squat exercise.', 'https://example.com/goblet-squat'),
(49, 'Sumo Squat', 'Legs', 'A basic sumo squat exercise.', 'https://example.com/sumo-squat'),
(50, 'Hack Squat', 'Legs', 'A basic hack squat exercise.', 'https://example.com/hack-squat'),
(51, 'Zercher Squat', 'Legs', 'A basic Zercher squat exercise.', 'https://example.com/zercher-squat'),
(52, 'Sissy Squat', 'Legs', 'A basic sissy squat exercise.', 'https://example.com/sissy-squat'),
(53, 'Jefferson Squat', 'Legs', 'A basic Jefferson squat exercise.', 'https://example.com/jefferson-squat'),
(54, 'Smith Machine Squat', 'Legs', 'A basic Smith machine squat exercise.', 'https://example.com/smith-machine-squat'),
(55, 'Leg Press Machine', 'Legs', 'A basic leg press machine exercise.', 'https://example.com/leg-press-machine'),
(56, 'Calf Press', 'Legs', 'A basic calf press exercise.', 'https://example.com/calf-press'),
(57, 'Seated Calf Raise', 'Legs', 'A basic seated calf raise exercise.', 'https://example.com/seated-calf-raise'),
(58, 'Standing Calf Raise', 'Legs', 'A basic standing calf raise exercise.', 'https://example.com/standing-calf-raise'),
(59, 'Toe Raise', 'Legs', 'A basic toe raise exercise.', 'https://example.com/toe-raise'),
(60, 'Single-Leg Deadlift', 'Legs', 'A basic single-leg deadlift exercise.', 'https://example.com/single-leg-deadlift'),
(61, 'Romanian Deadlift', 'Legs', 'A basic Romanian deadlift exercise.', 'https://example.com/romanian-deadlift'),
(62, 'Stiff-Leg Deadlift', 'Legs', 'A basic stiff-leg deadlift exercise.', 'https://example.com/stiff-leg-deadlift'),
(63, 'Sumo Deadlift', 'Legs', 'A basic sumo deadlift exercise.', 'https://example.com/sumo-deadlift'),
(64, 'Trap Bar Deadlift', 'Legs', 'A basic trap bar deadlift exercise.', 'https://example.com/trap-bar-deadlift'),
(65, 'Snatch-Grip Deadlift', 'Legs', 'A basic snatch-grip deadlift exercise.', 'https://example.com/snatch-grip-deadlift'),
(66, 'Deficit Deadlift', 'Legs', 'A basic deficit deadlift exercise.', 'https://example.com/deficit-deadlift'),
(67, 'Rack Pull', 'Legs', 'A basic rack pull exercise.', 'https://example.com/rack-pull'),
(68, 'Power Clean', 'Full Body', 'A basic power clean exercise.', 'https://example.com/power-clean'),
(69, 'Clean and Jerk', 'Full Body', 'A basic clean and jerk exercise.', 'https://example.com/clean-and-jerk'),
(70, 'Snatch', 'Full Body', 'A basic snatch exercise.', 'https://example.com/snatch'),
(71, 'Kettlebell Swing', 'Full Body', 'A basic kettlebell swing exercise.', 'https://example.com/kettlebell-swing'),
(72, 'Turkish Get-Up', 'Full Body', 'A basic Turkish get-up exercise.', 'https://example.com/turkish-get-up'),
(73, 'Medicine Ball Slam', 'Full Body', 'A basic medicine ball slam exercise.', 'https://example.com/medicine-ball-slam'),
(74, 'Battle Rope Wave', 'Full Body', 'A basic battle rope wave exercise.', 'https://example.com/battle-rope-wave'),
(75, 'Farmer''s Walk', 'Full Body', 'A basic farmer''s walk exercise.', 'https://example.com/farmers-walk'),
(76, 'Tire Flip', 'Full Body', 'A basic tire flip exercise.', 'https://example.com/tire-flip'),
(77, 'Sled Push', 'Full Body', 'A basic sled push exercise.', 'https://example.com/sled-push'),
(78, 'Sled Pull', 'Full Body', 'A basic sled pull exercise.', 'https://example.com/sled-pull'),
(79, 'Bear Crawl', 'Full Body', 'A basic bear crawl exercise.', 'https://example.com/bear-crawl'),
(80, 'Crab Walk', 'Full Body', 'A basic crab walk exercise.', 'https://example.com/crab-walk'),
(81, 'Inchworm', 'Full Body', 'A basic inchworm exercise.', 'https://example.com/inchworm'),
(82, 'High Knees', 'Full Body', 'A basic high knees exercise.', 'https://example.com/high-knees'),
(83, 'Butt Kicks', 'Full Body', 'A basic butt kicks exercise.', 'https://example.com/butt-kicks'),
(84, 'Jumping Jack', 'Full Body', 'A basic jumping jack exercise.', 'https://example.com/jumping-jack'),
(85, 'Star Jump', 'Full Body', 'A basic star jump exercise.', 'https://example.com/star-jump'),
(86, 'Tuck Jump', 'Full Body', 'A basic tuck jump exercise.', 'https://example.com/tuck-jump'),
(87, 'Plyo Push-Up', 'Chest', 'A basic plyo push-up exercise.', 'https://example.com/plyo-push-up'),
(88, 'Clap Push-Up', 'Chest', 'A basic clap push-up exercise.', 'https://example.com/clap-push-up'),
(89, 'Diamond Push-Up', 'Chest', 'A basic diamond push-up exercise.', 'https://example.com/diamond-push-up'),
(90, 'Wide Push-Up', 'Chest', 'A basic wide push-up exercise.', 'https://example.com/wide-push-up'),
(91, 'Decline Push-Up', 'Chest', 'A basic decline push-up exercise.', 'https://example.com/decline-push-up'),
(92, 'Incline Push-Up', 'Chest', 'A basic incline push-up exercise.', 'https://example.com/incline-push-up'),
(93, 'Handstand Push-Up', 'Shoulders', 'A basic handstand push-up exercise.', 'https://example.com/handstand-push-up'),
(94, 'Pike Push-Up', 'Shoulders', 'A basic pike push-up exercise.', 'https://example.com/pike-push-up'),
(95, 'Wall Sit', 'Legs', 'A basic wall sit exercise.', 'https://example.com/wall-sit'),
(96, 'Isometric Hold', 'Full Body', 'A basic isometric hold exercise.', 'https://example.com/isometric-hold'),
(97, 'Hollow Hold', 'Core', 'A basic hollow hold exercise.', 'https://example.com/hollow-hold'),
(98, 'Superman', 'Back', 'A basic superman exercise.', 'https://example.com/superman'),
(99, 'Bird Dog', 'Core', 'A basic bird dog exercise.', 'https://example.com/bird-dog'),
(100, 'Dead Bug', 'Core', 'A basic dead bug exercise.', 'https://example.com/dead-bug');

SET IDENTITY_INSERT Exercises OFF;